name: tts

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: tts
  cancel-in-progress: false

jobs:
  commit-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: git fetch origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - run: |
          chmod +x scripts/commit-msg
          for commit in $(git rev-list origin/${{ github.base_ref }}..HEAD); do
            if [ $(git show --no-patch --format=%P $commit | wc -w) -gt 1 ]; then continue; fi
            git show --no-patch --format=%B $commit > /tmp/commit_msg
            bash scripts/commit-msg /tmp/commit_msg || exit 1
          done

  deploy:
    runs-on: ubuntu-latest
    needs: commit-check
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          mkdir -p dist
          cp -r docs/* dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
