name: tts-release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        run: |
          git config user.name "harper-release-bot"
          git config user.email "237646224+harper-release-bot@users.noreply.github.com"

      - name: Run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.HARPER_RELEASE_BOT_TOKEN }}
          GH_TOKEN: ${{ secrets.HARPER_RELEASE_BOT_TOKEN }}
